mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
    - hyde.ext.plugins.blockdown.BlockdownPlugin
    - hyde.ext.plugins.less.LessCSSPlugin
meta:
    extends: columns.j2
    default_block: doc
    nodemeta: meta.yaml
    toc: root
    index: -1
    charset: utf-8
    compatibility: 'IE=edge,chrome=1'
    viewport: 'width=device-width, initial-scale=1.0'
    description: >
        El futuro tecnologico de la nación
        se construye con economia social
    title: tic@inaes — Comisión de Cooperativas Tecnólogicas
    keywords: >
                inaes,tic,cooperativas,floss
    author: Niv Sardi

context:
    data:
        site_title: tic@inaes
        author:
            name: Niv Sardi
            url: "http://tic.inaes.gob.ar"
        google_analytics_id: UA-XXXXX-YY
        home_url: index.html
        menu:
            - title: Home
              url: index.html
            - title: Promoción
              url: promo.html
            - title: Asesoría
              url: consulting.html
            - title: Código
              url: code.html
            - title: Trabajo
              url: jobs.html
            - title: Contacto
              url: who.html
    charset: utf-8